# Generated by Django 5.1.1 on 2024-09-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('non-cash', 'Безнал'), ('cash and non-cash', 'Частично наличные и частично безнал')], max_length=37, verbose_name='Способ оплаты(3 на выбор)'),
        ),
    ]
