# Generated by Django 5.1.1 on 2024-09-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_lesson_link_to_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lesson',
            field=models.ManyToManyField(related_name='lessons', to='materials.lesson', verbose_name='Уроки курса'),
        ),
    ]
