# Generated by Django 5.1.1 on 2024-10-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["pk"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
    ]
