# Generated by Django 5.1.1 on 2024-10-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_alter_lesson_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["pk"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
    ]
